### ISSUE TITLE
Compiling kernel scripts on target is broken

### ISSUE THREAD

**Issue by agherzan** [resin-os/module-headers#5] opened 2016-10-03 14:20 UTC
Reproduced on RPI3:

```
$ apt-get update
$ apt-get install gcc gzip2 git make build-essential
$ cd /tmp
$ wget files.resinstaging.io/images/raspberrypi3/1.8.0/kernel_modules_headers.tar.bz2
$ tar -xvf kernel_modules_headers.tar.bz2
$ git clone https://github.com/agherzan/dummy_lkm.git
$ cd dummy_lkm
$ make -C ../kernel_modules_headers scripts
[...]
  HOSTCC scripts/recordmcount
  HOSTCC scripts/sortextable
scripts/sortextable.c:31:32: fatal error: tools/be_byteshift.h: No such file or directory                        
 #include <tools/be_byteshift.h> 
                                ^                                                                                                                                                                               
compilation terminated.
scripts/Makefile.host:91: recipe for target 'scripts/sortextable' failed               
make[1]: *** [scripts/sortextable] Error 1
Makefile:555: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: Leaving directory '/tmp/kernel_modules_headers'
```

You can ignore the dummy git clone and compile directly in the kernel_modules_headers directory.

**Comment by ljskernel** [comment] 2016-10-04 16:35
Duplicate of #3

**Closed as completed by ljskernel** 2016-10-04 16:35 UTC
Labels: type/bug, close/duplicate
